# fly.toml app configuration file generated for simple-chatbot on 2024-10-28T20:25:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-chatbot'
primary_region = 'sjc'

[build]

[env]
  FLY_APP_NAME = 'simple-chatbot'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512'
  cpu_kind = 'shared'
  cpus = 1
